// Bairros de Maputo e Matola — usados em endereços e filtros de busca
export const MAPUTO_NEIGHBORHOODS = [
  "Polana Cimento A",
  "Polana Cimento B",
  "Polana Caniço",
  "Sommerschield",
  "Coop",
  "Alto-Maé A",
  "Alto-Maé B",
  "Malhangalene A",
  "Malhangalene B",
  "Central A",
  "Central B",
  "Central C",
  "Maxaquene A",
  "Maxaquene B",
  "Maxaquene C",
  "Maxaquene D",
  "Mafalala",
  "Chamanculo A",
  "Chamanculo B",
  "Chamanculo C",
  "Chamanculo D",
  "Xipamanine",
  "Aeroporto A",
  "Aeroporto B",
  "Costa do Sol",
  "Triunfo",
  "FPLM",
  "Hulene A",
  "Hulene B",
  "Mavalane A",
  "Mavalane B",
  "Laulane",
  "3 de Fevereiro",
  "Magoanine A",
  "Magoanine B",
  "Magoanine C",
  "Zimpeto",
  "Inhagoia A",
  "Inhagoia B",
  "Jardim",
  "Bagamoyo",
  "Luís Cabral",
  "Albazine",
  "Catembe",
  "Ka Tembe",
] as const;

export const MATOLA_NEIGHBORHOODS = [
  "Matola A",
  "Matola B",
  "Matola C",
  "Matola D",
  "Matola F",
  "Matola Gare",
  "Machava",
  "Machava Sede",
  "Infulene",
  "Liberdade",
  "Tsalala",
  "Boquisso",
  "Singathela",
  "Khongolote",
  "Ndlavela",
  "Patrice Lumumba",
] as const;

export function getNeighborhoodsForCity(city: string): string[] {
  if (city === "Maputo") return [...MAPUTO_NEIGHBORHOODS];
  if (city === "Matola") return [...MATOLA_NEIGHBORHOODS];
  return [];
}