project_id = "pfqruzusjjxyidhqkiob"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.emergency-sos]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
