import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';
import { createClient } from 'npm:@supabase/supabase-js@2';

// Province-specific health content templates
// In production, these would be generated by Gemini AI and cached
const PROVINCE_CONTENT: Record<string, { topics: string[]; priority: string }> = {
  'maputo_cidade': { topics: ['hipertensao', 'diabetes', 'saude mental', 'cancro'], priority: 'hipertensao' },
  'maputo_provincia': { topics: ['malaria', 'saude materna', 'higiene', 'nutricao'], priority: 'malaria' },
  'gaza': { topics: ['malaria', 'desnutricao', 'sarampo', 'saude materna'], priority: 'malaria' },
  'inhambane': { topics: ['malaria', 'hiv', 'saude materna', 'tuberculose'], priority: 'malaria' },
  'sofala': { topics: ['malaria', 'colera', 'saude materna', 'nutricao'], priority: 'malaria' },
  'manica': { topics: ['malaria', 'tuberculose', 'hiv', 'saude mental'], priority: 'tuberculose' },
  'tete': { topics: ['malaria', 'hiv', 'desnutricao', 'saude materna'], priority: 'hiv' },
  'zambezia': { topics: ['malaria', 'hiv', 'saude materna', 'desnutricao'], priority: 'malaria' },
  'nampula': { topics: ['malaria', 'hiv', 'saude materna', 'nutricao'], priority: 'malaria' },
  'niassa': { topics: ['malaria', 'tuberculose', 'hiv', 'saude materna'], priority: 'malaria' },
  'cabo_delgado': { topics: ['malaria', 'desnutricao', 'sarampo', 'saude materna'], priority: 'malaria' },
};

// Seasonal adjustments (malaria peak: Dec-Jun in Mozambique)
function getSeasonalPriority(topic: string): number {
  const month = new Date().getMonth(); // 0-11
  const rainySeason = month >= 11 || month <= 5; // Nov-May
  if (topic === 'malaria' && rainySeason) return 2;
  if (topic === 'colera' && rainySeason) return 2;
  if (topic === 'sarampo') return 1;
  return 1;
}

// Simple health tips database (would be AI-generated in production)
const HEALTH_TIPS: Record<string, string[]> = {
  malaria: [
    'Use mosquiteiro tratado com insecticida todas as noites. Inspeccione se tem rasgos ou buracos.',
    'Elimine agua parada ao redor da sua casa. Agua parada e o criadouro principal do mosquito.',
    'Se tiver febre, dor de cabeca e calafrios, va a unidade sanitaria imediatamente para fazer o teste de malaria.',
    'As gravidas devem fazer o teste de malaria em cada consulta pre-natal. A malaria na gravidez e perigosa.',
    'Complete todo o tratamento de malaria, mesmo que os sintomas desaparecam. Nao pare de tomar os medicamentos.',
  ],
  hiv: [
    'Tomar o ARV todos os dias na mesma hora e a adesao ao tratamento melhora a sua saude e reduz o risco de transmissao.',
    'O tratamento ARV permite viver uma vida longa e saudavel. Nao interrompa mesmo que se sinta bem.',
    'Se esqueceu de tomar o ARV, tome assim que lembrar. Nunca tome duas doses ao mesmo tempo.',
    'Faca o teste de VIH regularmente. O diagnostico precoce permite iniciar o tratamento a tempo.',
  ],
  saude_materna: [
    'Gravidas devem fazer pelo menos 4 consultas pre-natais. A primeira consulta deve ser o mais cedo possivel.',
    'Tomar ferro e acido folico durante a gravidez previne anemia e malformacoes no bebe.',
    'Ir a unidade sanitaria imediatamente se tiver sangramento, dor de cabeca intensa ou visao turva durante a gravidez.',
  ],
  hipertensao: [
    'Reduza o consumo de sal. O sal em excesso aumenta a pressao arterial e o risco de AVC.',
    'Verifique a sua pressao arterial regularmente. A hipertensao nao tem sintomas mas e silenciosa e perigosa.',
    'Faca pelo menos 30 minutos de exercicio por dia. Caminhar e uma forma simples e eficaz de controlar a pressao.',
  ],
  diabetes: [
    'Reduza o consumo de acucar e alimentos processados. Prefira alimentos naturais e frescos.',
    'Faca o teste de glicemia regularmente, especialmente se tiver historico familiar de diabetes.',
    'Os pes diarios ajudam a detectar precocemente sinais de diabetes. Consulte um medico se notar feridas que nao cicatrizam.',
  ],
  tuberculose: [
    'Se tiver tosse por mais de 2 semanas, suor nocturno ou perda de peso, va a unidade sanitaria fazer o teste de TB.',
    'O tratamento da TB dura 6 meses e deve ser completado na totalidade. Interromper gera resistencia.',
    'A TB e curavel. Faca o teste gratuito na unidade sanitaria mais proxima.',
  ],
  desnutricao: [
    'Diversifique a alimentacao da sua familia. Combine cereais, leguminosas, vegetais e frutas em cada refeicao.',
    'Cricas menores de 2 anos devem ser amamentadas exclusivamente ate os 6 meses. O leite materno protege contra doencas.',
    'Se a crianca estiver com peso abaixo do normal, leve a unidade sanitaria para avaliacao nutricional.',
  ],
  colera: [
    'Lave as maos com sabao antes de comer e depois de usar a casa de banho. A higiene e a melhor prevencao contra o colera.',
    'Beba apenas agua tratada ou fervida. A agua contaminada e a principal via de transmissao do colera.',
    'Se tiver diarreia liquida abundante e vomitos, va a unidade sanitaria imediatamente. O colera pode ser fatal em horas.',
  ],
  saude_mental: [
    'Falar sobre os seus sentimentos nao e sinal de fraqueza. Procure apoio de pessoas de confianca ou profissionais de saude.',
    'O exercicio fisico regular ajuda a reduzir stress e ansiedade. Caminhar 20 minutos por dia faz diferenca.',
    'Se tiver dificuldade em dormir, ansiedade persistente ou tristeza prolongada, consulte um profissional de saude mental.',
  ],
  nutricao: [
    'Uma alimentacao equilibrada inclui: arroz/massa, feijao/ervilha, legumes, fruta e proteina (peixe/carne/ovos).',
    'Beba pelo menos 2 litros de agua por dia. A desidratacao causa fadiga, dor de cabeca e diminui a concentracao.',
    'As frutas e legumes da estacao sao mais baratos e mais nutritivos. Aproveite a abundancia local.',
  ],
  sarampo: [
    'A vacina contra o sarampo e gratuita nas unidades sanitarias. Certifique-se de que os seus filhos estao vacinados.',
    'O sarampo e altamente contagioso. Se suspeitar de sarampo, isole a pessoa e va a unidade sanitaria.',
  ],
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    const body = await req.json().catch(() => ({}));
    const province = body?.province_id as string | undefined;
    const count = Math.min((body?.count as number) || 1, 5);

    // Pick a random topic based on province + season
    let targetProvince = province;
    if (!targetProvince) {
      // Get all provinces with users and pick one
      const { data: profiles } = await supabase
        .from('profiles')
        .select('province_id')
        .not('province_id', 'is', null)
        .limit(100);
      const provinces = [...new Set((profiles || []).map(p => p.province_id))];
      targetProvince = provinces[Math.floor(Math.random() * provinces.length)] || 'maputo_cidade';
    }

    const config = PROVINCE_CONTENT[targetProvince] || PROVINCE_CONTENT['maputo_cidade'];

    // Weight topics by seasonal priority
    const weightedTopics = config.topics.map(t => ({
      topic: t,
      weight: getSeasonalPriority(t)
    }));

    // Pick random topic with weighting
    const totalWeight = weightedTopics.reduce((s, t) => s + t.weight, 0);
    let r = Math.random() * totalWeight;
    let selectedTopic = config.topics[0];
    for (const t of weightedTopics) {
      r -= t.weight;
      if (r <= 0) { selectedTopic = t.topic; break; }
    }

    // Pick tips for this topic
    const tips = HEALTH_TIPS[selectedTopic] || HEALTH_TIPS['malaria'];
    const selectedTips: string[] = [];
    const available = [...tips];
    for (let i = 0; i < count && available.length > 0; i++) {
      const idx = Math.floor(Math.random() * available.length);
    selectedTips.push(available.splice(idx, 1)[0]);
    }

    // Queue notifications for all active users in this province
    let queued = 0;
    if (body?.queue) {
      const { data: users } = await supabase
        .from('profiles')
        .select('user_id')
        .eq('province_id', targetProvince)
        .limit(500);

      if (users?.length) {
        const notifs = users.map((u, i) => ({
          user_id: u.user_id,
          category: 'health_tip',
          title: `Dica de Saude - ${selectedTopic.replace(/_/g, ' ')}`,
          body: selectedTips[i % selectedTips.length],
          deep_link: 'medwallet://educacao',
          scheduled_at: new Date(Date.now() + i * 5000).toISOString(), // Stagger 5s apart
          metadata: { topic: selectedTopic, province: targetProvince, auto_generated: true }
        }));

        const { error } = await supabase
          .from('automated_notifications')
          .insert(notifs);
        queued = notifs.length - (error ? notifs.length : 0);
      }
    }

    return json({
      province: targetProvince,
      topic: selectedTopic,
      tips: selectedTips,
      queued_for_delivery: queued,
      seasonal: new Date().getMonth() >= 11 || new Date().getMonth() <= 5
        ? 'estacao chuvosa (malaria alta)' : 'estacao seca'
    });

  } catch (e) {
    return json({ error: (e as Error).message }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    status,
  });
}