org.gradle.jvmargs=-Xmx1400m -XX:MaxMetaspaceSize=400m -XX:+UseSerialGC
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Ajustes para caixa de 4GB (evitar OOM do cgroup)
org.gradle.workers.max=2
org.gradle.parallel=false
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
org.gradle.java.home=/home/z/my-project/tools/jdk17
org.gradle.caching=false
org.gradle.configuration-cache=false
