// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY: Credentials must be provided via environment variables only.
// Hard-coded fallbacks are intentionally removed to prevent credential leakage.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const _hasCredentials = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!_hasCredentials) {
  console.error(
    "CRITICAL: Supabase credentials missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Safe Supabase client — null when credentials are missing so the app
 * can degrade gracefully instead of crashing with a blank white screen.
 */
export const supabase: SupabaseClient<Database> = _hasCredentials
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: typeof window !== 'undefined' ? window.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        // SECURITY: Use PKCE flow instead of implicit to prevent token interception
        flowType: 'pkce',
      }
    })
  : (null as unknown as SupabaseClient<Database>);

export const isSupabaseConfigured = _hasCredentials;